[package]
name = "leptess"
version = "0.7.4"
authors = ["QP Hou <dave2008713@gmail.com>"]
description = "Rust binding for Tesseract and Leptonica."
homepage = "https://github.com/houqp/leptess"
repository = "https://github.com/houqp/leptess"
readme = "README.md"
keywords = ["leptonica", "tesseract", "ocr"]
license = "MIT"
documentation = "https://houqp.github.io/leptess/leptess/index.html"

[dependencies]
leptonica-sys = "0.2.0"
tesseract-sys = "0.3.0"
