version: 2

jobs:
  test:
    docker:
      - image: cirepo/rust:1.33.0-bionic
    steps:
      - checkout
      - run:
          name: install leptonica & tesseract
          command: |
              echo 'deb http://deb.debian.org/debian stretch-backports main' | tee -a /etc/apt/sources.list<Paste>
              apt-get update
              apt-get -t stretch-backports -y install libleptonica-dev libtesseract-dev=4.0.0-2~bpo9+1 tesseract-ocr-eng
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test --all

workflows:
  version: 2
  workflow:
    jobs:
      - test
